### ISSUE TITLE
link to tutorial is broken

### ISSUE THREAD

**Issue by anthony0727** [pnnl/DeepDataProfiler#47]
seems like link to below tutorial is broken(in README), 
[Tutorial 2 - Topological Data Analysis](https://colab.research.google.com/github/pnnl/DeepDataProfiler/blob/master/tutorials/Tutorial%202%20-%20DDPAlgorithms.ipynb)

is it the same one as below?
[DeepDataProfiler](https://github.com/pnnl/DeepDataProfiler)/[tutorials](https://github.com/pnnl/DeepDataProfiler/tree/master/tutorials)/Tutorial 2 - DDPGraph-Homology.ipynb

Thanks!
Anthony

**Comment by brendapraggastis** [comment]
Yes it is. Let us know if it isn't working for you.
